### ISSUE TITLE
Error on line 7 in the define_word script

### ISSUE THREAD

**Issue by PietJanHein** [BreadOnPenguins/scripts#2]
When I downloaded the script I noticed an issue, you probably overlooked it because you don't use it in the shell but directly start it with a hotkey, consequently you don't see the error. 

On line 7 in the script you have to put the variable inside quotation marks. See the screenshot. 
![image](https://github.com/user-attachments/assets/25b0fd24-fdc9-4475-bc41-c2a3fef0ca97)

I changed it into this: 
 [ -z "$query" ] && notify-send -h string:bgcolor:#bf616a -t 3000 "Invalid word." && exit 0
Now I don't get an error while running the script.

**Comment by BreadOnPenguins** [comment]
Just updated to fix - thank you!

**Comment by PietJanHein** [comment]
Great! See the discussions-section for 2 alternative solutions (2 variants) which people might find useful.
